version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    ignore:
      # Old versions are pinned for libocr.
      - dependency-name: github.com/libp2p/go-libp2p-core
      - dependency-name: github.com/libp2p/go-libp2p-peerstore
      - dependency-name: github.com/multiformats/go-multiaddr
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
