variables:
  IMAGE_REPOSITORY: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/test-infra-definitions

stages:
  - test
  - build

integration-testing:
  stage: test
  image: $IMAGE_REPOSITORY/runner:8388801b
  tags: ["runner:docker"]
  before_script:
    # Setup AWS Credentials
    - mkdir -p ~/.aws
    - aws ssm get-parameter --region us-east-1 --name ci.test-infra-definitions.agent-qa-profile --with-decryption --query "Parameter.Value" --out text >> ~/.aws/config
    - export AWS_PROFILE=agent-qa-ci
    - pulumi login "s3://dd-pulumi-state?region=us-east-1&awssdk=v2&profile=$AWS_PROFILE"
    - pip install -r requirements.txt
  script:
    - bash tests/invoke-tasks-test.sh
  

build-runner-image:
  stage: build
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10.13
  tags: ["runner:docker"]
  variables:
    PUSH_IMAGE: "false"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        PUSH_IMAGE: "true"
    - when: on_success
  script:
    - TARGET_REPO="${IMAGE_REPOSITORY}/runner"
    - if [ "$PUSH_IMAGE" = "true" ]; then PUSH_ARG="--push"; fi
    # Tag with 8 and 12 SHA to match go.mod
    - docker buildx build --no-cache --pull $PUSH_ARG --tag ${TARGET_REPO}:${CI_COMMIT_SHORT_SHA} --tag ${TARGET_REPO}:${CI_COMMIT_SHA:0:12}  .
  retry: 2

