language: scala
sudo: false
dist: trusty
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.1
jdk:
  - oraclejdk8
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.8
install:
  - sudo apt-get --yes install python-pygments
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
cache:
  directories:
    - $HOME/.ivy2/cache
