language: scala
sudo: false
scala:
  - 2.11.12
  - 2.12.7
  - 2.13.0-M5
jdk:
  - oraclejdk8
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.7
install:
  - sudo apt-get --yes install python-pygments
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
cache:
  directories:
    - $HOME/.ivy2/cache
