[package]
name = "betterquesting_report"
version = "0.1.0"
authors = ["J2ghz <j2.00ghz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive="1.0.114"
serde_json="1.0.56"
serde="1.0.114"