[package]
name = "tokio-websockets"
version = "0.2.0"
edition = "2021"
description = "High performance, strict, tokio-util based websockets implementation"
repository = "https://github.com/Gelbpunkt/tokio-websockets/"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
fastrand = { version = "1.7", default-features = false }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
tokio = { version = "1", default-features = false, features = ["net", "io-util", "rt"] }
tokio-util = { version = "0.7", default-features = false, features = ["codec"] }

# SHA-1 fallback when no TLS is enabled
sha1_smol = { version = "1.0", optional = true }

# SIMD
simdutf8 = { version = "0.1", default-features = false, features = ["std", "public_imp", "aarch64_neon"], optional = true }

# Client
base64 = { version = "0.13", optional = true }
http = { version = "0.2", default-features = false, optional = true }
http-body = { version = "0.4", default-features = false, optional = true }
httparse = { version = "1.6", optional = true }

# Native TLS
tokio-native-tls = { version = "0.3", optional = true }

# Rustls
ring = { version = "0.16", default-features = false, optional = true }
rustls-native-certs = { version = "0.6", optional = true }
tokio-rustls = { version = "0.23", optional = true }
webpki-roots = { version = "0.22", optional = true }

# Users can manually tune into OpenSSL for SHA-1 when native-tls is enabled
openssl = { version = "0.10", default-features = false, optional = true }

[features]
default = ["client", "server", "sha1_smol"]
client = ["base64", "http", "httparse"]
http-integration = ["http-body"]
server = ["base64", "http", "httparse"]
simd = ["simdutf8"]
native-tls = ["tokio-native-tls"]
rustls-webpki-roots = ["tokio-rustls", "ring", "webpki-roots"]
rustls-native-roots = ["tokio-rustls", "ring", "rustls-native-certs"]

[dev-dependencies]
# For tests
hyper = { version = "0.14", default-features = false, features = ["client", "http1", "tcp"] }
# This is just a little bit of performance tuning
parking_lot = { version = "0.12", default-features = false, features = ["nightly", "hardware-lock-elision"] }
tokio = { version = "1", default-features = false, features = ["net", "macros", "parking_lot", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.18", default-features = false, features = ["connect"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
