[package]
name = "tokio-websockets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
tokio = { version = "1", default-features = false, features = ["net"] }
tokio-util = { version = "0.6", default-features = false, features = ["codec"] }

# SIMD
simdutf8 = { version = "0.1", default-features = false, features = ["std", "public_imp", "aarch64_neon"], optional = true }

# Client
base64 = { version = "0.13", optional = true }
http = { version = "0.2", default-features = false, optional = true }
http-body = { version = "0.4", default-features = false, optional = true }

[features]
default = ["client"]
client = ["base64"]
http-integration = ["http", "http-body"]
simd = ["simdutf8"]

[dev-dependencies]
hyper = { version = "0.14", default-features = false, features = ["client", "tcp", "http1"] }
tokio = { version = "1", default-features = false, features = ["net", "macros", "rt-multi-thread"] }

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
