version: "3.7"
services:
  lido-depositor-bot:
    image: lidofinance/depositor-bot
    build: .
    container_name: lido-depositor-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:8080
    environment:
      - SCRIPT_NAME=depositor
      - NETWORK=${NETWORK}
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - KAFKA_BROKER_ADDRESS_1=${KAFKA_BROKER_ADDRESS_1}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - MAX_GAS_FEE=${MAX_GAS_FEE}
      - GAS_FEE_PERCENTILE=${GAS_FEE_PERCENTILE}
      - GAS_FEE_PERCENTILE_DAYS_HISTORY=${GAS_FEE_PERCENTILE_DAYS_HISTORY}
      - GAS_PRIORITY_FEE_PERCENTILE=${GAS_PRIORITY_FEE_PERCENTILE}
      - CONTRACT_GAS_LIMIT=${CONTRACT_GAS_LIMIT}
      - MIN_BUFFERED_ETHER=${MIN_BUFFERED_ETHER}

  lido-pause-bot:
    image: lidofinance/depositor-bot
    build: .
    container_name: lido-pause-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9001:8080
    environment:
      - SCRIPT_NAME=pauser
      - NETWORK=${NETWORK}
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - KAFKA_BROKER_ADDRESS_1=${KAFKA_BROKER_ADDRESS_1}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
