apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: vboulineau-ecs
spec:
#  backend: "gs://vboulineau-pulumi-test"
  envRefs:
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        key: AWS_SECRET_ACCESS_KEY
    GOOGLE_CREDENTIALS:
      type: Secret
      secret:
        name: pulumi-gs-auth
        key: sa-key
    PULUMI_CONFIG_PASSPHRASE:
      type: Secret
      secret:
        name: pulumi-config-pass
        key: pass
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-token
        key: token
  gitAuth:
    accessToken:
      type: Secret
      secret:
        name: pulumi-git-auth
        key: git-pat
  stack: vboulineau-ecs
  projectRepo: https://github.com/vboulineau/pulumi-definitions.git
  repoDir: ecscluster
  branch: refs/heads/main
  destroyOnFinalize: true
  config:
    aws:region: us-east-1
    PREFIX: vboulineau
    ENVIRONMENT: sandbox
