[tool.poetry]
name = "depositor-bot"
version = "4.0.0"
description = "Bot that collects council signatures, checks blockchain state and signatures and do deposits. Also pause bot send pause tx if there is security warning."
authors = ["Raman <roman.s@p2p.org>"]
license = "MIT License"
readme = "README.md"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "1.23.2"
prometheus-client = "0.14.1"
confluent-kafka = "1.9.2"
timeout-decorator = "^0.5.0"
web3-multi-provider = "^0.4.1"
schema = "^0.7.5"
web3 = "^5.30.0"
flashbots = "^1.0.2"
"stomp.py" = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[tool.pytest.ini_options]
pythonpath = [
  "src",
  "tests",
]