---
- name: Ensure the PowerDNS configuration directory exists
  file: name={{pdns_rec_config_dir | default('/etc/powerdns')}} state=directory owner="root" group="root"

- name: Add configuration for the PowerDNS Recursor
  template: src=recursor.conf.j2 dest={{pdns_rec_config_dir | default('/etc/powerdns')}}/recursor.conf
  notify: Restart PowerDNS Recursor
