---

- name: Extract the PowerDNS Recursor Version from YUM
  yum_madison:
    name: "pdns-recursor"
    update_cache: yes
  changed_when: False
  register: pdns_recursor_version_result

- name: Export the pdns_recursor_version variable for RedHat
  set_fact:
    pdns_recursor_version: pdns_recursor_version: |
      {{ pdns_recursor_version_result.versions | map(attribute='version') | sort(reverse=True) | first }}
