---

- name: Import the PowerDNS Recursor 'master' APT repository key
  apt_key:
    url: http://repo.powerdns.com/CBC8B383-pub.asc
    id: D47975F8DAE32700A563E64FFF389421CBC8B383
  when: pdns_rec_repo_provider == "powerdns" and pdns_rec_repo_branch == "master"

- name: Import the PowerDNS Recursor '4.0.x' APT repository key
  apt_key:
    url: http://repo.powerdns.com/FD380FBB-pub.asc
    id: 9FAAA5577E8FCF62093D036C1B0C6205FD380FBB
  when: pdns_rec_repo_provider == "powerdns" and pdns_rec_repo_branch in ["40"]

- name: Pinning the PowerDNS packages to the PowerDNS APT repo
  copy:
    dest: /etc/apt/preferences.d/pdns
    src: pdns.pin
    owner: root
    group: root
    mode: 0644
  when: pdns_rec_repo_provider == "powerdns"

- name: Add the PowerDNS Recursor APT repository
  apt_repository:
    repo: "deb [arch=amd64] http://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-{{ pdns_rec_repo_branch }} main"
  when: pdns_rec_repo_provider == "powerdns"

- name: Install the PowerDNS Recursor package
  apt:
    name: pdns-recursor
    state: present
    update_cache: yes
