---

- name: Get the name of the package
  set_fact:
    pdns_rec_pkg_name: "{{ pdns_rec_url.split('/')[-1] }}"

- name: Get the version of the package
  set_fact:
    pdns_rec_pkg_version: "{{ pdns_rec_pkg_name.split('_')[-2] }}"

- name: Grab the package
  get_url:
    url: "{{ pdns_rec_url }}"
    dest: "/tmp/{{ pdns_rec_pkg_name }}"
    checksum: "{{ pdns_rec_url_checksum }}"

- name: Pinning the pdns-recursor package to the downloaded version
  template:
    src: pdns-recursor.pin
    dest: /etc/apt/preferences.d/pdns

- name: Install the package, ignoring dependency errors
  apt:
    deb: "/tmp/{{ pdns_rec_pkg_name }}"
  failed_when: False

- name: Install dependencies
  command: apt-get -f install
