---

- name: Get the PowerDNS Recursor package name
  set_fact:
    pdns_rec_pkg_name: "{{ pdns_rec_url.split('/')[-1] }}"

- name: Get the PowerDNS Recursor package version
  set_fact:
    pdns_rec_pkg_version: "{{ pdns_rec_pkg_name.split('_')[-2] }}"

- name: Download the PowerDNS Recursor package
  get_url:
    url: "{{ pdns_rec_url }}"
    dest: "/tmp/{{ pdns_rec_pkg_name }}"
    checksum: "{{ pdns_rec_url_checksum }}"

- name: Pin the PowerDNS Recursor package to the downloaded version
  template:
    src: pdns-recursor.pin
    dest: /etc/apt/preferences.d/pdns-recursor
  when: ansible_os_family == "Debian"

- name: Install the PowerDNS Recursor package with APT
  apt: deb="/tmp/{{ pdns_rec_pkg_name }}"
  failed_when: False
  when: ansible_os_family == "Debian"

- name: Install the PowerDNS Recursor package APT dependencies
  command: apt-get -f install
  when: ansible_os_family == "Debian"

- name: Install the PowerDNS Recursor package with YUM
  yum: name="/tmp/{{ pdns_rec_pkg_name }}" state=present
