---

- name: Include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "repo-{{ ansible_os_family }}.yml"
  when: pdns_rec_install_repo
  tags:
    - install
    - repository

- include: "inspect-{{ ansible_os_family }}.yml"
- include: configure.yml
  tags:
    - config

- include: install-epel.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- name: Install the PowerDNS Recursor package
  package:
    name: pdns-recursor
    state: present
  tags:
    - install

- name: Start and enable the PowerDNS Recursor service
  service:
    name: pdns-recursor
    state: started
    enabled: true
  tags:
    - service
