---

- name: Include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Validating role variables
  include: validate.yml

- include: "install-{{ pdns_rec_installation_type }}.yml"
  tags:
    - "{{ pdns_rec_installation_type }}"
    - install

- include: configure.yml
  tags:
    - conf
    - config
    - configuration

# TODO
#- include: install.source-debian.yml
#  when: pdns_installation_type == "source" and ansible_os_family == "Debian"
#  tags:
#    - source
#    - install
#
# TODO
#- include: install.source-redhat.yml
#  when: pdns_installation_type == "source" and ansible_os_family == "RedHat"
#  tags:
#    - source
#    - install


- name: Start and enable the PowerDNS Recursor service
  service:
    name: pdns-recursor
    state: started
    enabled: true
  tags:
    - service
