---

- name: Include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: validate.yml

- include: "repo-{{ ansible_os_family }}.yml"
  when: pdns_rec_repo_provider != "os"
  tags:
    - install
    - repository

- include: "inspect-{{ ansible_os_family }}.yml"
- include: configure.yml
  tags:
    - config

- include: install.yml
  tags:
    - install

- name: Start and enable the PowerDNS Recursor service
  service:
    name: pdns-recursor
    state: started
    enabled: true
  tags:
    - service
