---

- name: Include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: validate.yml

- include: "repo-{{ ansible_os_family }}.yml"
  when: pdns_rec_repo_provider == "powerdns"
  tags:
    - install
    - repository

- include: "inspect-{{ ansible_os_family }}.yml"

- name: Export the pdns_recursor_version variable
  set_fact:
    pdns_recursor_version: "{{ pdns_recursor_version_result['stdout'].split('-')[0] }}"

- include: configure.yml
  tags:
    - conf
    - config
    - configuration

- include: install.yml
  tags:
    - install

- name: Start and enable the PowerDNS Recursor service
  service:
    name: pdns-recursor
    state: started
    enabled: true
  tags:
    - service
