version: '3.8'
services:
  postgres:
    image: 'postgres:15.2-alpine'
    restart: always
    environment:
      - POSTGRES_USER=functions
      - POSTGRES_PASSWORD=functions
      - POSTGRES_DB=functions_development
    ports:
      - '5432:5432'
    healthcheck:
      test: 'pg_isready -U functions -d functions_development -p 5432'
      interval: 2s
      timeout: 5s
      retries: 5