name: Run autobahn testsuite and publish results

on:
  push:
    branches:
      - main

jobs:
  autobahn:
    name: Run autobahn testsuite and publish results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Prepare directories
        run: |
          mkdir autobahn/reports
          echo "<!DOCTYPE html><html><head><title>Autobahn test suite results</title></head><body><a href="clients/index.html">Clients</a><br><a href="servers/index.html">Servers</a></body></html>" > autobahn/reports/index.html

      - name: Build tokio-websockets (no SIMD) and tokio-tungstenite
        run: |
          cargo build --release --examples

      - name: Build tokio-websockets (SIMD)
        env:
          RUSTFLAGS: -C target-cpu=haswell
        run: |
          cargo build --release --examples --features simd
          mv target/release/examples/autobahn_client target/release/examples/autobahn_client_simd
          mv target/release/examples/autobahn_server target/release/examples/autobahn_server_simd

      - name: Run testsuite
        run: |
          ./scripts/autobahn_client_ci.sh
          ./scripts/autobahn_server_ci.sh

      - name: Upload results to GitHub pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: autobahn/reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
