name: Check links in OpenAPI spec

on: [push]

jobs:
  linkChecker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.6
        with:
          args: -c .github/lychee.toml openapi.json --verbose