name: Pull Request Checks
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master

jobs:
  build:
    name: Changelog
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Check Changelog
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md
          noChangelogLabel: my custom label # default `no changelog`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
