name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: |
          poetry install

      - name: Test with pytest
        run: |
          poetry run pytest tests
        env:
          NETWORK: ${{ secrets.NETWORK }}
          WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
          KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
          KAFKA_BROKER_ADDRESS_1: ${{ secrets.KAFKA_BROKER_ADDRESS_1 }}
          KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
