name: Lint Wording
on: [pull_request]

jobs:
  prose:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.3
      with:
        # Optional
        files: openapi.json
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}